export enum IpcEvents {
  CLEAR_CONSOLE = "CLEAR_CONSOLE",
  OUTPUT_ENTRY = "OUTPUT_ENTRY",
  PROJECT_RUN = "PROJECT_RUN",
  PROJECT_PACKAGE = "PROJECT_PACKAGE",
  PROJECT_MAKE = "PROJECT_MAKE",
  SHOW_INACTIVE = "SHOW_INACTIVE",
  BEFORE_QUIT = "BEFORE_QUIT",
  CONFIRM_QUIT = "CONFIRM_QUIT",
  FS_OPEN_PROJECT = "FS_OPEN_PROJECT",
  FS_SAVE_PROJECT = "FS_SAVE_PROJECT",
}

export const ipcMainEvents = [
  IpcEvents.OUTPUT_ENTRY,
  IpcEvents.SHOW_INACTIVE,
  IpcEvents.BEFORE_QUIT,
  IpcEvents.CONFIRM_QUIT,
];

export const ipcRendererEvents = [
  IpcEvents.CLEAR_CONSOLE,
  IpcEvents.PROJECT_RUN,
  IpcEvents.PROJECT_PACKAGE,
  IpcEvents.PROJECT_MAKE,
  IpcEvents.FS_SAVE_PROJECT,
  IpcEvents.FS_OPEN_PROJECT,
];

export const WEBCONTENTS_READY_FOR_IPC_SIGNAL =
  "WEBCONTENTS_READY_FOR_IPC_SIGNAL";
